services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: django-insecure-6o+1#dp(^s=^p9u241kihz3k!y5sl-co75ve)we5ukoszqqb!& 
        generateValue: true
